addSbtPlugin("com.timushev.sbt" % "sbt-updates"  % "0.7.0")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype" % "3.12.2")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"      % "2.3.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt" % "2.6.1")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix" % "0.14.7")
